spring:
  application:
    name: shell
  shell:
    interactive:
      enabled: true

servidor:
  path-ficheros: C:/Users/fjimenez/OneDrive/Documentos/Home/Shell
  path-google: G:/Mi unidad/Databases

logging:
  file: 
    name: C:/Projects/Personal/logs/shell.log
    path: C:/Projects/Personal/logs

---
spring:
  config:
    activate:
      on-profile: windows

logging:
  file: 
    name: C:/Projects/Personal/logs/shell.log
    path: C:/Projects/Personal/logs

servidor:
  path-ficheros: C:/Users/fjimenez/OneDrive/Documentos/Home/Shell
